[theme]
primaryColor = "#58A6FF"
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#161B22"
textColor = "#C9D1D9"
font = "sans serif"

[server]
headless = true
port = 8501
maxUploadSize = 200

[browser]
gatherUsageStats = false
